---
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/molecule-template'

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:    
          name: Create virtual env
          command: |
            virtualenv venv
            source venv/bin/activate

      - run:
          name: Install python dependencies
          command: |
            pip install -r requirements.txt
      
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            molecule test

      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports