language: node_js
node_js:
  - "v11"
  - "v10"
  - "v8"

jobs:
  include:
    - stage: "Test"
      cache:
        directories:
          - node_modules
      
      script: yarn test-ci

    - stage: "NPM release"
      branches:
        only:
          - master
      script: npm run semantic-release
