language: node_js

jobs:
  include:
    - stage: Test
      cache:
        directories:
          - node_modules
      node_js:
        - v11
        - v10
        - v8
      script: yarn test-ci

    - stage: NPM release
      if: branch = master
      node_js:
        - v10
      script: npm run semantic-release