---
language: node_js
cache:
  directories:
    - node_modules

install:
  - travis_retry yarn

script: yarn test-ci

jobs:
  include:
    - stage: test
      if: branch != master
      name: "Test"
      node_js: lts/*
    
    - stage: release
      name: "Release"
      if: branch = master
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
