---
language: node_js
cache:
  directories:
    - node_modules

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: develop
      script: yarn test-ci
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
