name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn

      - name: Set git credentials for test
        run: git config –global user.name “John Smith”

      - run: yarn run test
